spring:
  application:
    name: study8-mini
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
camunda:
  bpm:
    admin-user:
      id: ${CAMUNDA_USERNAME}
      password: ${CAMUNDA_PASSWORD}
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
