spring:
  application:
    name: study8-camunda
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
camunda:
  bpm:
    admin-user:
      id: ${CAMUNDA_USERNAME}
      password: ${CAMUNDA_PASSWORD}
    filter:
      create: All tasks
server:
  port: 8090